# Generated by Django 3.2.5 on 2023-03-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='last_edit',
            field=models.DateTimeField(null=True),
        ),
    ]
